spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: chatdb
  main:
    allow-bean-definition-overriding: true


server:
  port: 8088


custom:
  url:
    frontend-url: http://localhost:5173
  jwt:
    secretKey: your-secret-key-value
